name       : python-service-identity
version    : 17.0.0
release    : 4
source     :
    - https://pypi.python.org/packages/de/2a/cab6e30be82c8fcd2339ef618036720eda954cf05daef514e386661c9221/service_identity-17.0.0.tar.gz : 4001fbb3da19e0df22c47a06d29681a398473af4aa9d745eca525b3b2c2302ab
license    : MIT
component  : programming.python
summary    : Service identity verification for pyOpenSSL.
description: |
    Service identity verification for pyOpenSSL.
builddeps  :
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-asn1-modules
    - python-attrs
    - python-idna
    - python-openssl
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
