name       : python-service-identity
version    : 17.0.0
release    : 6
source     :
    - https://github.com/pyca/service_identity/archive/17.0.0.tar.gz : 5d1596394655d7f6597bd8adda16b43b2e3341d6d9fd95a9a1f6ff17c5098dc6
license    : MIT
component  : programming.python
summary    : Service identity verification for pyOpenSSL.
description: |
    Service identity verification for pyOpenSSL.
builddeps  :
    - python-attrs
    - python-asn1-modules
    - python-cryptography
    - python-pytest
    - python-setuptools
rundeps    :
    - python-asn1-modules
    - python-attrs
    - python-idna
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        PYTHONPATH=$PWD/build/lib py.test -v
    popd

    pushd $PKG_BUILD_DIR/py3build
        PYTHONPATH=$PWD/build/lib py.test3 -v
    popd
