name       : python-service-identity
version    : 18.1.0
release    : 9
source     :
    - https://files.pythonhosted.org/packages/9a/3d/9eb0563e066ea0540cf580695593ab079376e920016d4d1b3ff2fd8abf4b/service_identity-18.1.0.tar.gz : 0858a54aabc5b459d1aafa8a518ed2081a285087f349fe3e55197989232e2e2d
license    : MIT
component  : programming.python
summary    : Service identity verification for pyOpenSSL.
description: |
    Service identity verification for pyOpenSSL.
builddeps  :
    - python-attrs
    - python-asn1-modules
    - python-cryptography
    - python-pytest
    - python-setuptools
rundeps    :
    - python-asn1-modules
    - python-attrs
    - python-idna
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
