name       : python-service-identity
version    : 21.1.0
release    : 13
source     :
    - https://github.com/pyca/service-identity/archive/refs/tags/21.1.0.tar.gz : 541294ad6060c10e28554f36bb1c154e11f71ad3e23a160eea62eff9bf50522c
homepage   : https://pypi.org/project/service_identity/
license    : MIT
component  : programming.python
summary    : Service identity verification for pyOpenSSL
description: |
    Service identity verification for pyOpenSSL.
builddeps  :
    - python-asn1-modules
    - python-attrs
    - python-cryptography
    - python-idna
    - python-pytest
rundeps    :
    - python-asn1-modules
    - python-attrs
    - python-cryptography
    - python-idna
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
