name       : python-service-identity
version    : 17.0.0
release    : 5
source     :
    - https://files.pythonhosted.org/packages/source/s/service_identity/service_identity-17.0.0.tar.gz : 4001fbb3da19e0df22c47a06d29681a398473af4aa9d745eca525b3b2c2302ab
license    : MIT
component  : programming.python
summary    : Service identity verification for pyOpenSSL.
description: |
    Service identity verification for pyOpenSSL.
builddeps  :
    - python-attrs
    - python-asn1-modules
    - python-cryptography
    - python-openssl
    - python-setuptools
rundeps    :
    - python-asn1-modules
    - python-attrs
    - python-idna
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        python setup.py test
    popd

    pushd $PKG_BUILD_DIR/py3build
        python3 setup.py test
    popd
