name       : python-service-identity
version    : 18.1.0
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/s/service_identity/service_identity-18.1.0.tar.gz : 0858a54aabc5b459d1aafa8a518ed2081a285087f349fe3e55197989232e2e2d
homepage   : https://pypi.org/project/service_identity/
license    : MIT
component  : programming.python
summary    : Service identity verification for pyOpenSSL
description: |
    Service identity verification for pyOpenSSL.
builddeps  :
    - python-asn1-modules
    - python-attrs
    - python-cryptography
    - python-pytest
rundeps    :
    - python-asn1-modules
    - python-attrs
    - python-cryptography
    - python-idna
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
