name       : python-service-identity
version    : 16.0.0
release    : 2
source     :
    - https://pypi.python.org/packages/source/s/service_identity/service_identity-16.0.0.tar.gz : 0630e222f59f91f3db498be46b1d879ff220955d7bbad719a5cb9ad14e3c3036
license    : MIT
summary    : Service identity verification for pyOpenSSL.
description: |
    Service identity verification for pyOpenSSL.
builddeps  :
    - pkgconfig(python-2.7)
    - pkgconfig(python-3.5)
    - python-setuptools
rundeps    :
    - python-asn1-modules
    - python-attrs
    - python-idna
build      : |
    for py in "python" "python3" ; do
        ${py} setup.py build
    done
install    : |
    for py in "python" "python3" ; do
        ${py} setup.py install --root=%installroot% --no-compile -O0
    done
